# Change these first
owner: RickCogley # Your GitHub username
repo: esolia-uptime # Your GitHub repository name
user-agent: RickCogley

# Add your sites here
sites:
  - name: PROdb Cloud Database PaaS
    url: https://pro.dbflex.net
    icon: https://assets.esolia.com/eSolia-Chicklet-Color-512px.ico
  - name: PROdb Cloud Database API Endpoint
    url: https://pro.dbflex.net/secure/api/v2/15331/$PRODB_TOKEN_15331/Res%3A%20Random%20Quotation/Default%20View/select.json 
    icon: https://assets.esolia.com/eSolia-Chicklet-Color-512px.ico
  - name: eSolia Newsletter System
    url: https://send.esolia.pro
    icon: https://assets.esolia.com/eSolia-Chicklet-Color-512px.ico
  - name: eSolia Secure Text Sharing System
    url: https://salty.esolia.pro
    icon: https://assets.esolia.com/eSolia-Chicklet-Color-512px.ico
  - name: eSolia Screen Connect
    url: https://esolia.screenconnect.com
    icon: https://assets.esolia.com/eSolia-Chicklet-Color-512px.ico
  - name: eSolia.com English Site
    url: https://esolia.com
  - name: eSolia.co.jp Japanese Site
    url: https://esolia.co.jp

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.esolia.pro
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://assets.esolia.com/eSolia_Square_Chicklet_Logo_YellowBlue.svg
  name: eSolia Uptime
  introTitle: "eSolia Uptime Monitor Status"
  introMessage: Welcome to our uptime monitor status page, built with real-time data from a [GitHub repository](https://github.com/RickCogley/esolia-uptime) using GitHub Actions, Issues, and Pages. Powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
